name: Build and Deeply Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: macos-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: install python v 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
